--注释
CREATE TABLE IF NOT EXISTS logging_timestamp (
  id BIGINT(10) NOT NULL, 
  timestamp BIGINT);  
  
--注释
CREATE TABLE IF NOT EXISTS QRTZ_CALENDARS (
  CALENDAR_NAME VARCHAR (200)  NOT NULL ,
  CALENDAR IMAGE NOT NULL
);
--注释
CREATE TABLE IF NOT EXISTS QRTZ_CRON_TRIGGERS (
  TRIGGER_NAME VARCHAR (200)  NOT NULL ,
  TRIGGER_GROUP VARCHAR (200)  NOT NULL ,
  CRON_EXPRESSION VARCHAR (120)  NOT NULL ,
  TIME_ZONE_ID VARCHAR (80) 
);